### ISSUE TITLE
NetKAN AVC support for split distributions

### ISSUE THREAD

**Issue by Ippo343** [KSP-CKAN/CKAN-netkan#10]
_From @KevinCathcart on November 6, 2014 3:48_

When a single distribution is split into multiple packages (like is sometimes done for configs, or to separate out optional parts), and the original distribution contains only one .version file, only the package that will include that version file can use it to set the KSP version information.

It would be nice if there were some way for all the packages from that single distribution to use that single version file.

_Copied from original issue: KSP-CKAN/CKAN#269_

**Comment by pjf** [comment]
Pretty sure we support this now, so closing. :)
