### ISSUE TITLE
Curse support

### ISSUE THREAD

**Issue by Ippo343** [KSP-CKAN/CKAN-netkan#12]
_From @BobPalmer on October 21, 2014 2:51_

I didn't see it floating around, but given the request for folks to use repos *other* than the official one, you should really consider Curse support if you wish for this project to achieve a more universal adoption rate.  

_Copied from original issue: KSP-CKAN/CKAN#115_

**Comment by pjf** [comment]
Closing without re-opening the original. We're not going to be doing any scraping of Curse data without an explicit OK from Curse. It definitely breaks the spirit of their terms of service, and is just plain impolite. Sorry.
