### ISSUE TITLE
Spec extension proposal: Github release asset match

### ISSUE THREAD

**Issue by BasharMilesTeg** [KSP-CKAN/CKAN-netkan#22]
Some Github repos contain releases for more than one mod or their releases should be distinguished in some way. This already occurs with the [prerelease flag](https://github.com/KSP-CKAN/CKAN-netkan/blob/master/Github/GithubAPI.cs#L61) ([issue #3](https://github.com/KSP-CKAN/CKAN-netkan/issues/3)). My proposal is to create a way of performing a regex match on the assets.name field returned by the Github API.

Two possible ways of adding this to the schema are:
* Provide a token of the format #/ckan/github/:user/:repo/\<regex> similar to the proposed [source releases](https://github.com/KSP-CKAN/CKAN-netkan/issues/11).
* Provide an optional field "match" similar to [filter_regexp](https://github.com/KSP-CKAN/CKAN/blob/master/CKAN.schema#L171).

In both cases, if the asset name does not [match](http://msdn.microsoft.com/en-us/library/system.text.regularexpressions.regex.ismatch%28v=vs.100%29.aspx) the regex, it would be discarded is the same manner as an asset with a non-matching prerelease flag is discarded.

Three examples of how this feature could used with mods CKAN is already indexing are:
* [Environmental Visual Enhancements](https://github.com/rbray89/EnvironmentalVisualEnhancements/releases) provides 'regular' and 'low res' assets that could be split into two mods. If the [asset.name field returned by the Github API](https://api.github.com/repos/rbray89/EnvironmentalVisualEnhancements/releases) matches the regex "LR\\.zip$" then that asset would be included when inflating a .netkan for "Environmental Visual Enhancements - Low Res".
* [AnimatedDecouplers](https://github.com/Starwaster/AnimatedDecouplers/releases) provides 'regular' and 'x64' assets that could take advantage of the proposed ["supported_arch" and "supported_os"](https://github.com/KSP-CKAN/CKAN/issues/489) extension. A "x64\\.zip$" regex would differentiate between the "supported_arch".
* [Modular Fuel System and Real Fuels](https://github.com/NathanKell/ModularFuelSystem/releases) share a repo. With this proposal and download url rewriting similar to the source releases proposal, both mods could have their releases handled automatically by NetKAN.

**Comment by pjf** [comment]
I like this idea. Just to check and clarify, are we proposing a way of of matching only on the asset name, or a combination of asset name and some other attribute (eg: tag name, release title, etc)?

Matching just on the asset name *sounds* like it's sufficient for what we're after¹, in which case I'd suggest `#/ckan/github/:user/:repo/asset_match/:regexp` as the descriptor. The reason for having an `asset_match` segment is that it means we can support other extensions in the future (such as `#/ckan/github/:user/:repo/src` referenced above).

---

¹ I could only find Real Fuel releases in the Real Fuels (aka Modular Fuel Systems) repo linked to from above; if there really are dual releases, that makes things more complex.

**Comment by BasharMilesTeg** [comment]
Yes, my proposal is for a way of performing a regex match on the asset name.

I agree that asset name is probably sufficient as [API /releases](https://api.github.com/repos/NathanKell/ModularFuelSystem/releases) appears to only include tags with assets attached. If it's found to not be, an additional '/tag_match' (or whatever is appropriate) segment can be added in a later revision. The only complication would come from needing to match multiple fields.

[RealFuels v8.3](https://github.com/NathanKell/ModularFuelSystem/releases/tag/rf-v8.3); [Modular Fuel Tanks 5.4.0](https://github.com/NathanKell/ModularFuelSystem/releases/tag/mft-5.4.0). It would be straightforward to rewrite the download url to http://taniwha.org/~bill/ModularFuelTanks_v5.4.0.zip ([forum thread](http://forum.kerbalspaceprogram.com/threads/64117)). [API /tags](https://api.github.com/repos/NathanKell/ModularFuelSystem/tags) isn't chronologically ordered. This is getting away from this proposal and into the source releases proposal and url rewriting.

**Comment by hakan42** [comment]
Asked @rbray89 for a little support in packaging EVE. @BasharMilesTeg , would you mind terribly to open seperate issues in CKAN-netkan for EVE, AnimatedDecouplers and the Modular Fuels?

**Comment by BasharMilesTeg** [comment]
I've opened issues (and PR's) for AnimatedDecouplers and EnvironmentalVisualEnhancements but am not sure what to do about ModularFuelSystem as the existing [RealFuels.netkan](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/RealFuels.netkan) seems to have RealFuels covered and I don't know if there is a way of using the MFT tags to trigger NetKAN

**Comment by hakan42** [comment]
Thank you so very much... 

If we already have a way to handle them, I would leave RealFuels be. No need to fix all the world at once :smile:

Also, I believe Alexander did take care of the the pre-existing ATM files...
