### ISSUE TITLE
The netkan bot won't pick up multple releases if they are released too close to each other

### ISSUE THREAD

**Issue by hakan42** [KSP-CKAN/CKAN-netkan#23]
_From @Ippo343 on December 20, 2014 9:24_

The bot refreshes the index about once an hour. However, it seems to assume that only one release has appeared since the last update.

Case study: we missed a FAR release. If you look at the changelog on kerbalstuff, there is a v0.14.4.1 release that hasn't been indexed by the bot. This is because ferram4 has released v0.14.4.1 and v0.14.5 within minutes of each other and the bot only picked up the latest one, ignoring the other one.

Poking @pjf and @AlexanderDzhoganov : we might want to improve the bot's detection of new releases.

_Copied from original issue: KSP-CKAN/NetKAN#236_

**Comment by hakan42** [comment]
_From @AlexanderDzhoganov on January 3, 2015 0:28_

This should be in CKAN-netkan, could you move it?

**Comment by pjf** [comment]
re-opening original
