### ISSUE TITLE
KSP-AVC inflator fails on one-line version strings

### ISSUE THREAD

**Issue by hakan42** [KSP-CKAN/CKAN-netkan#36]
As remarked on KSP-CKAN/NetKAN#505 , KSP-CKAN/NetKAN#507 and https://github.com/RemoteTechnologiesGroup/RemoteTech/pull/292, we can't expand version strings in one combined string:

```
"VERSION": "1.6.0",
```

throws an JSON exception while deserializing, while the three-part version:

```
     "VERSION":{
         "MAJOR":1,
         "MINOR":6,
         "PATCH":0
     },
```

works correctly. As a stopgap, I am opening issues at the target project, but it would be nice if netkan would not crash and burn on theoretically valid .version files.

**Comment by pjf** [comment]
It looks like the KSP-AVC documentation ( http://ksp.cybutek.net/kspavc/Documents/README.htm ) doesn't mention the simple strings, but yes, they do seem to be treated as valid by AVC.

We can probably use a JsonConverter internally to do this. Converting a string to a `CKAN.Version` object is *easier* than converting a JSON object into one.

cc'ing @taraniselsu, as this came up in IRC.
