### ISSUE TITLE
Support globbing/wildcards in "find" and "file" statement

### ISSUE THREAD

**Issue by TeddyDD** [KSP-CKAN/CKAN-netkan#41]
Related to KSP-CKAN/NetKAN#658

I'm not sure but currently there is no way to install all files from zip root directory and there is no way to create netkan for mods like Module Manager (and BackgroundProcessing) witch contains version numbers in dll file name (like ModuleManager.2.5.9.dll)

I suggest something like this
```json
"install":[{
    "file": "ModuleManager.*.dll",
    "install_to": "GameData"
}]
```
I think this should be supported only on netkan side. netkan.exe should compile this to:
```json
"install":[{
    "find": "ModuleManager.2.5.9.dll",
    "install_to": "GameData"
}]
```

**Comment by Dazpoet** [comment]
Looks like https://github.com/KSP-CKAN/CKAN-core/pull/131 should be relevant to this issue.

**Comment by TeddyDD** [comment]
It seems so. I'm closing this now.
