### ISSUE TITLE
NetKan HTTPS download failure on Windows

### ISSUE THREAD

**Issue by dbent** [KSP-CKAN/CKAN-netkan#50]
Using [latest version of netkan](https://github.com/KSP-CKAN/CKAN-nightly/releases/tag/jenkins-NetKAN-146), I get the following error when attempting to use it on Windows.

```
> netkan .\PlaneMode.netkan

Unhandled Exception: System.Exception: Curl download failed with error SslCaCert
   at CKAN.NetKAN.Web.DownloadString(String url)
   at CKAN.NetKAN.KSAPI.Call(String path)
   at CKAN.NetKAN.KSAPI.Mod(Int32 mod_id)
   at CKAN.NetKAN.MainClass.KerbalStuff(JObject orig_metadata, String remote_id, NetFileCache cache)
   at CKAN.NetKAN.MainClass.Main(String[] args)
```

The error indicates that CurlSharp via libcurl can't verify the SSL certificate of the host (Kerbal Stuff, in this case). After some investigating, I was able to get it to work by downloading [`curl-ca-bundle.crt`](https://github.com/masroore/CurlSharp/blob/master/libs/amd64/curl-ca-bundle.crt) and setting `easy.CaInfo` to its file path in [Web.cs](https://github.com/KSP-CKAN/CKAN-netkan/blob/master/Web.cs) per the CurlSharp [SSLGet example](https://github.com/masroore/CurlSharp/blob/d2d56993f0cc125dd8e89ef48f908eafd5e18484/Samples/SSLGet/SSLGet.cs).

My suspicion is that libcurl performs some sort of automatic lookup for the system CA bundle on Linux machines, which does not work on Windows, requiring explicitly setting the path. *However*, I cannot find any such use of the `CaInfo` property in CKAN, which functions normally for me.

**Comment by Dazpoet** [comment]
aye new versions of netkan are screwed on windows. You need to go way back to the middle of the 120's to get one working natively on windows. Reason is at https://github.com/KSP-CKAN/CKAN-netkan/pull/45 and some more work is done in subsequent PRs.

Very awesome work on finding a workaround and providing info though so a dev can start tracking it down :)
