### ISSUE TITLE
Explicit Epoch in NetKAN files

### ISSUE THREAD

**Issue by dbent** [KSP-CKAN/CKAN-netkan#51]
Since NetKAN files usually get their version number automatically, I was wondering if there's a way to explicitly set an epoch in the NetKAN file? If a NetKAN  indexed mod changes their versioning scheme what's the strategy to specify a new epoch?

I would think the .netkan could contain something like:
```json
{
    "$epoch": "1"
}
```

And any .ckan it generates would have that epoch number automatically applied:
```json
{
    "version": "1:x.y.z"
}
```
In the case where the upstream version is simply `x.y.z`.

Or maybe `epoch` should be treated as its own property separate from `version`, in which case no special logic is needed, but could potentially create backwards incompatibility in the spec.

**Comment by TeddyDD** [comment]
> Or maybe epoch should be treated as its own property separate from version, in which case no special logic is needed, but could potentially create backwards incompatibility in the spec.

I think this one is better. CKAN and Netkan specs should be as similar as possible so this change should apply to CKAN-core as well.

**Comment by Dazpoet** [comment]
See #60 and rejoice!

Working example can be found in https://github.com/KSP-CKAN/NetKAN/pull/1433
