### ISSUE TITLE
NetKAN Dependency versioning for split distributions

### ISSUE THREAD

**Issue by Ippo343** [KSP-CKAN/CKAN-netkan#9]
_From @KevinCathcart on November 6, 2014 3:48_

When a single distribution is split into multiple packages (like is sometimes done for configs, or to separate out optional parts), and one of those packages depend on another, it would be useful to be able to specify that the version of that other package must be the same as the version of the current one.  

While dependency version requirements can be specified with `version` there appears to be no way to have NetKAN substitute in the version it discovered from the `$kref`.

_Copied from original issue: KSP-CKAN/CKAN#270_

**Comment by pjf** [comment]
re-opening original
